name: iosApp
options:
  bundleIdPrefix: com.example.pickii
packages:
  KakaoOpenSDK:
    url: https://github.com/kakao/kakao-ios-sdk
    from: 2.28.0
targets:
  iosApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - iosApp
    configFiles:
      Debug: Config/Secrets.xcconfig
      Release: Config/Secrets.xcconfig
    dependencies:
      - package: KakaoOpenSDK
        product: KakaoSDKCommon
      - package: KakaoOpenSDK
        product: KakaoSDKAuth
      - package: KakaoOpenSDK
        product: KakaoSDKUser
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.pickii.spike
        SWIFT_VERSION: 5.0
        CODE_SIGN_STYLE: Automatic
        FRAMEWORK_SEARCH_PATHS: "$(SRCROOT)/../shared/build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME)"
        ENABLE_USER_SCRIPT_SANDBOXING: NO
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
    info:
      path: Generated-Info.plist
      properties:
        UILaunchScreen: {}
        CADisableMinimumFrameDurationOnPhone: true
        KakaoNativeAppKey: $(KAKAO_NATIVE_APP_KEY)
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - kakao$(KAKAO_NATIVE_APP_KEY)
        LSApplicationQueriesSchemes:
          - kakaokompassauth
          - kakaolink
          - kakaoplus
    preBuildScripts:
      - name: Compile Kotlin Framework
        script: |
          if [ "YES" = "$OVERRIDE_KOTLIN_BUILD_IDE_SUPPORTED" ]; then
            echo "Skipping Gradle build task invocation due to OVERRIDE_KOTLIN_BUILD_IDE_SUPPORTED environment variable set to \"YES\""
            exit 0
          fi
          cd "$SRCROOT/.."
          ./gradlew :shared:embedAndSignAppleFrameworkForXcode
        basedOnDependencyAnalysis: false
  iosAppUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - iosAppUITests
    settings:
      base:
        SWIFT_VERSION: 5.0
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: YES
        TEST_TARGET_NAME: iosApp
    dependencies:
      - target: iosApp
schemes:
  iosApp:
    build:
      targets:
        iosApp: all
        iosAppUITests: [test]
    test:
      targets:
        - iosAppUITests
    run:
      config: Debug
